<?php
$email = (!empty($user)) ? $user["email"] : "";
$name = (!empty($user)) ? $user["name"] : "";
if (!empty($error)) {
foreach ($error as $e) {
?>
<div class="alert alert-danger">
  <?php echo $e ?>
</div>

<?php }}?>
<?php 

$form = $this->form;
$form->prepare();
$form->setAttribute('action',$this->url('user', ['action' => 'add']) );
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('opwd'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
 ?>
