<?php

if (!empty($error)) {
    foreach ($error as $e) {
        ?>
<br>
<div class="alert alert-danger">
  <?php echo $e ?>
</div>

<?php }}?>


<?php 

$form = $this->form;
$form->prepare();
$form->setAttribute('action',$this->url('user', ['action' => 'update', "id" => $user["_id"]]) );
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo '<label>'.$this->formRow($form->get('pwd_checkbox')).' Change Password</label>';
echo '<div class="form-group" id="old_pass">';
echo $this->formRow($form->get('opwd')->setAttribute('id','opwd')->setLabel("Old Password:"));
echo '</div>';
echo '<div class="form-group" id="new_pass">';
echo $this->formRow($form->get('opwd')->setAttribute('name','npwd')->setAttribute('id','npwd')->setLabel("New Password:"));
echo '</div>';
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
 ?>
