<?php

if (!empty($error)) {
    foreach ($error as $e) {
        ?>
<br>
<div class="alert alert-danger">
  <?php echo $e ?>
</div>

<?php }}?>

<form action=<?=$this->url('user', ['action' => 'update', "id" => $user["_id"]])?> method="post" onsubmit="passValidator(event)">
  <div class="form-group">
    <label for="name">Name:</label>
    <input required type="name" class="form-control" id="name" name="name" value="<?php echo $user["name"] ?>">
  </div>
  <div class="form-group">
    <label for="email">Email address:</label>
    <input required type="email" class="form-control" id="email" name="email" value="<?php echo $user["email"] ?>">
  </div>


  <input  type="checkbox" name="pwd_checkbox" onclick="toggleNewPass(this)" value="1" >Change Password:
  <br>
  <div class="form-group" id="old_pass">
    <label for="pwd">Password:</label>
    <input  type="password" class="form-control" id="opwd" name="opwd" minlength="6">
  </div>
  <div class="form-group" id="new_pass">
    <label for="pwd">New Password:</label>
    <input  type="password" class="form-control" id="npwd" name="npwd">
  </div>
  <br>

  <button type="submit" class="btn btn-default">Submit</button>
</form>

